apiVersion: skaffold/v2beta6
kind: Config
metadata:
  name: ticketing
build:
  local:
    push: false
  artifacts:
    - image: xteleon/auth
      context: auth
deploy:
  kubectl:
    manifests:
      - infra/k8s/*
