apiVersion: skaffold/v2beta6
kind: Config
metadata:
  name: ticketing
build:
  local:
    push: false
  artifacts:
    - image: xteleon/auth
      context: auth
    - image: xteleon/client
      context: client
    - image: xteleon/ticket
      context: ticket
    - image: xteleon/orders
      context: orders
    - image: xteleon/expiration
      context: expiration
deploy:
  kubectl:
    manifests:
      - infra/k8s/*
