apiVersion: apps/v1
kind: Deployment
metadata:
  name: expiration-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: expiration
  template:
    metadata:
      labels:
        app: expiration
    spec:
      containers:
        - name: expiration
          image: xteleon/expiration
          env:
            - name: BROKER_USER
              valueFrom:
                secretKeyRef:
                  name: rabbitmq-secret
                  key: RABBIT_USER
            - name: BROKER_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: rabbitmq-secret
                  key: RABBIT_PASSOWORD
            - name: BROKER_VHOST
              valueFrom:
                secretKeyRef:
                  name: rabbitmq-secret
                  key: RABBIT_VHOST
