apiVersion: apps/v1
kind: Deployment
metadata:
  name: ticket-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ticket
  template:
    metadata:
      labels:
        app: ticket
    spec:
      containers:
        - name: ticket
          image: xteleon/ticket
          env:
            - name: JWT_KEY
              valueFrom:
                secretKeyRef:
                  name: jwt-secret
                  key: JWT_KEY
            - name: BROKER_USER
              valueFrom:
                secretKeyRef:
                  name: rabbitmq-secret
                  key: RABBIT_USER
            - name: BROKER_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: rabbitmq-secret
                  key: RABBIT_PASSOWORD
            - name: BROKER_VHOST
              valueFrom:
                secretKeyRef:
                  name: rabbitmq-secret
                  key: RABBIT_VHOST
---
apiVersion: v1
kind: Service
metadata:
  name: ticket-cluster-ip-srv
spec:
  type: ClusterIP
  selector:
    app: ticket
  ports:
    - protocol: TCP
      port: 6000
      targetPort: 6000
